modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All rights reserved"
#issueTrackerURL="https://github.com/Example/Example/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://github.com/Example/Example"
#logoFile="examplemod.png"# A text field displayed in the mod UI
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"